[package]
name = "bjorn-wordcount-text"
version = "0.1.0"
edition = "2021"

[dependencies]
bjorn = { path = "../../lib/bjorn" }
anyhow = { workspace = true }
clap = { workspace = true }
regex = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
