[package]
name = "fs_sort"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
memmap2 = "0.9"
memchr = "2.7"
